description:
  map_name: "test_field"
  date: "08.09.23"
  text: "bla-bla"
  complete: 100

border:
  type: 'border'
  coordinates: [ [ 10, 10 ], [ 1270, 10 ], [ 1270, 710 ], [ 10, 710 ] ]

objects:
  circle_1:
    type: 'circle'
    center: [ 1000, 200 ]
    radius: 80

  circle_2:
    type: 'circle'
    center: [ 200, 500 ]
    radius: 80

  square_1:
    type: 'rectangle'
    coordinates: [ [ 100, 100 ], [ 100, 250 ], [ 250, 250 ], [ 250, 100 ] ]

  square_2:
    type: 'rectangle'
    coordinates: [ [ 800, 500 ], [ 800, 600 ], [ 1050, 600 ], [ 1050, 500 ] ]