description:
  map_name: "test_field"
  date: "08.09.23"
  text: "bla-bla"
  complete: 100

border:
  type: 'border'
  coordinates: [ [ 10, 10 ], [ 1270, 10 ], [ 1270, 710 ], [ 10, 710 ] ]

circles:
  circle_1:
    center: [1000, 200]
    radius: 80
  circle_2:
    center: [200, 500]
    radius: 80

rectangles:
  square_1:
    coordinates: [[100, 100], [100, 250], [250, 250], [250, 100]]
  square_2:
    coordinates: [[800, 500], [800, 600], [1050, 600], [1050, 500]]